// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApVgtaYW32aLHnqPg1agkuwEnGWb7-Ync',
    appId: '1:272673119329:web:02bc7841a7aa01a8ca1e20',
    messagingSenderId: '272673119329',
    projectId: 'cinemood-4bbe2',
    authDomain: 'cinemood-4bbe2.firebaseapp.com',
    databaseURL: 'https://cinemood-4bbe2-default-rtdb.firebaseio.com',
    storageBucket: 'cinemood-4bbe2.firebasestorage.app',
    measurementId: 'G-FVC1KXGTV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rX1QXv9QNiuY-TC9ha-mxjWzIdd__zw',
    appId: '1:272673119329:android:837e6edc08f711fcca1e20',
    messagingSenderId: '272673119329',
    projectId: 'cinemood-4bbe2',
    databaseURL: 'https://cinemood-4bbe2-default-rtdb.firebaseio.com',
    storageBucket: 'cinemood-4bbe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd76VxmeCOXadQ3QZHOYdMUqQ_2s6xgMI',
    appId: '1:272673119329:ios:1106abad3a5849f3ca1e20',
    messagingSenderId: '272673119329',
    projectId: 'cinemood-4bbe2',
    databaseURL: 'https://cinemood-4bbe2-default-rtdb.firebaseio.com',
    storageBucket: 'cinemood-4bbe2.firebasestorage.app',
    iosBundleId: 'com.cinemood.cinemood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd76VxmeCOXadQ3QZHOYdMUqQ_2s6xgMI',
    appId: '1:272673119329:ios:1106abad3a5849f3ca1e20',
    messagingSenderId: '272673119329',
    projectId: 'cinemood-4bbe2',
    databaseURL: 'https://cinemood-4bbe2-default-rtdb.firebaseio.com',
    storageBucket: 'cinemood-4bbe2.firebasestorage.app',
    iosBundleId: 'com.cinemood.cinemood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApVgtaYW32aLHnqPg1agkuwEnGWb7-Ync',
    appId: '1:272673119329:web:f782a4979d63cd7bca1e20',
    messagingSenderId: '272673119329',
    projectId: 'cinemood-4bbe2',
    authDomain: 'cinemood-4bbe2.firebaseapp.com',
    databaseURL: 'https://cinemood-4bbe2-default-rtdb.firebaseio.com',
    storageBucket: 'cinemood-4bbe2.firebasestorage.app',
    measurementId: 'G-VWHSF3MSWL',
  );
}
